// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCPZd9reSwxBFCnVVt30CQRqwzlTUOM58',
    appId: '1:883530810558:web:9327310b9974dc05d88aef',
    messagingSenderId: '883530810558',
    projectId: 'push-notifications-cf725',
    authDomain: 'push-notifications-cf725.firebaseapp.com',
    storageBucket: 'push-notifications-cf725.firebasestorage.app',
    measurementId: 'G-S8NFL0Z3KV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7LYRBrrzHzJ41FFRAyVh7i9yjro_iwkM',
    appId: '1:883530810558:android:01050bede1f9b5cad88aef',
    messagingSenderId: '883530810558',
    projectId: 'push-notifications-cf725',
    storageBucket: 'push-notifications-cf725.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSIPyXOAQBzs916gT0Bae3rFGOJiIiA4E',
    appId: '1:883530810558:ios:90bd53b1cee87bdbd88aef',
    messagingSenderId: '883530810558',
    projectId: 'push-notifications-cf725',
    storageBucket: 'push-notifications-cf725.firebasestorage.app',
    iosBundleId: 'com.example.housingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSIPyXOAQBzs916gT0Bae3rFGOJiIiA4E',
    appId: '1:883530810558:ios:90bd53b1cee87bdbd88aef',
    messagingSenderId: '883530810558',
    projectId: 'push-notifications-cf725',
    storageBucket: 'push-notifications-cf725.firebasestorage.app',
    iosBundleId: 'com.example.housingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCPZd9reSwxBFCnVVt30CQRqwzlTUOM58',
    appId: '1:883530810558:web:9a3de62d7ab75513d88aef',
    messagingSenderId: '883530810558',
    projectId: 'push-notifications-cf725',
    authDomain: 'push-notifications-cf725.firebaseapp.com',
    storageBucket: 'push-notifications-cf725.firebasestorage.app',
    measurementId: 'G-9J7047416L',
  );

}